const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  createPlaceholder: (gameName) => ipcRenderer.invoke('create-placeholder', gameName),
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  close: () => ipcRenderer.send('window-close'),
  updateRPC: (data) => ipcRenderer.send('update-rpc', data),
  onRPCStatus: (callback) => ipcRenderer.on('rpc-status', (event, ...args) => callback(...args)),
  searchGame: (query) => ipcRenderer.invoke('search-steam-game', query),
  getGameDetails: (appId) => ipcRenderer.invoke('get-game-details', appId),
  generateLua: (data) => ipcRenderer.invoke('generate-lua', data),
  checkLuaExists: (appId) => ipcRenderer.invoke('check-lua-exists', appId),
  removeLua: (appId) => ipcRenderer.invoke('remove-lua', appId),
  restartSteam: () => ipcRenderer.invoke('restart-steam'),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  loadSettings: () => ipcRenderer.invoke('load-settings'),
  getMyGames: () => ipcRenderer.invoke('get-my-games'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  getResourcePath: (relativePath) => ipcRenderer.invoke('get-resource-path', relativePath),
  generateKey: () => ipcRenderer.invoke('generate-key'),
  validateKey: (key, deviceId) => ipcRenderer.invoke('validate-key', key, deviceId),
  markKeyUsed: (key, deviceId) => ipcRenderer.invoke('mark-key-used', { key, deviceId }),
  startDownloadUpdate: () => ipcRenderer.invoke('start-download-update'),
  quitAndInstall: () => ipcRenderer.invoke('quit-and-install'),
  onUpdateAvailable: (callback) => ipcRenderer.on('update-available', (event, ...args) => callback(...args)),
  onUpdateNotAvailable: (callback) => ipcRenderer.on('update-not-available', (event, ...args) => callback(...args)),
  onUpdateDownloadProgress: (callback) => ipcRenderer.on('update-download-progress', (event, ...args) => callback(...args)),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update-downloaded', (event, ...args) => callback(...args)),
  onUpdateError: (callback) => ipcRenderer.on('update-error', (event, ...args) => callback(...args)),
});